spring:
  profiles:
    include: druid,mybatisplus
    active: dev
  application:
    name: busi
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
management:
  server:
    port: 8082
  endpoints:
    jmx:
      exposure:
        include: '*'
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always